linters:
  enable:
    - copyloopvar
    - depguard
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        deny:
          - pkg: "github.com/hashicorp/terraform-plugin-sdk/v2/helper/acctest"
            desc: "Use github.com/hashicorp/terraform-plugin-testing/helper/acctest"
          - pkg: "github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
            desc: "Use github.com/hashicorp/terraform-plugin-testing/helper/resource"
          - pkg: "github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
            desc: "Use github.com/hashicorp/terraform-plugin-testing/terraform"
          - pkg: "github.com/hashicorp/terraform-plugin-sdk/v2"
            desc: "Use Terraform Plugin Framework"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
